name: flutter_app
description: My journey to learn Flutter

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.0.0
  provider: ^6.0.5
  easy_localization: ^3.0.1
  flutter_form_builder: ^9.0.0
  form_builder_validators: ^9.0.0
  sizer: ^2.0.15
  shared_preferences: ^2.0.17
  english_words: ^4.0.0
  go_router: ^9.0.3
  percent_indicator: ^4.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/translations/

  fonts:
    - family: "Lato"
      fonts:
        - asset: assets/fonts/Lato-Regular.ttf
          weight: 400
    - family: "Montserrat"
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
          weight: 300

